can_pro={
'MIRON_WGT':'铁水重量',
'FURNACESEQ':'炉龄',
'SPRAYGUNSEQ':'枪龄',
'SUBLANCE_AGE':'副枪枪龄',
'HOTMETALWGT':'铁水装入量(kg)',
'COLDPIGWGT':'生铁装入量(kg)',
'SCRAPWGT':'废钢装入量(kg)',
'RETURNSTEELWEIGHT':'回炉钢液量(kg)',
'L96053601':'钢渣',
'HEAT_WGT':'炉重(KG)',
'DOWNFURNACETIMES':'倒炉次数',
'O_CONT':'定氧',
'STEELWGT':'出钢量',
'TIMEOFOXYGEN':'一倒供氧时间',
'D1_TEMP_VALUE':'第一次测温值',
'D2_TEMP_VALUE':'第二次测温值',	
}






PRO_BOF_HIS_ALLFIELDS={
                                'MIRON_WGT':'铁水重量',
								'MIRON_TEMP':'铁水温度',
								'MIRON_C':'铁水C含量',
								'MIRON_SI':	'铁水SI含量',
								'MIRON_MN':'铁水MN含量',
								'MIRON_P':'铁水P含量',
								'MIRON_S':'铁水S含量',
								'SCRAP_NUM':'废钢数量',
								'scrap_96053101':'大渣钢',
								'scrap_96052200':'自产废钢',
								'scrap_16010101':'重型废钢',
								'scrap_16020101':'中型废钢',
								'scrap_16030101':'未知废钢',
								'scrap_16040101':'破碎废钢',
								'scrap_96052501':'小渣钢',
								'FURNACESEQ':'炉龄',
								'SPRAYGUNSEQ':'枪龄',
								'HOTMETALWGT':'铁水装入量(kg)',
								'COLDPIGWGT':'生铁装入量(kg)',
								'SCRAPWGT':'废钢装入量(kg)',
								'SLAGWGT':'渣钢(kg)',
								'RETURNSTEELWEIGHT':'回炉钢液量(kg)',
								'IS_TEMP':'铁水入炉温度',
								'L12010302':'石灰石_40-70mm',
								'L12010601':'萤石_FL80',
								'L12020201':'增碳剂',
								'L12020301':'低氮增碳剂',
								'L13010101':'硅铁_Si72-80%、AL≤2%(粒度10-60mm)',
								'L13010301':'微铝硅铁_Si 72-80%、AL≤0.1%、Ti≤0.1%',
								'L13020101':'硅锰合金_Mn 65-72%、Si 17-20%',
								'L13020201':'高硅硅锰_Mn ≥60%、Si ≥27%',
								'L13040400':'中碳铬铁',
								'L96020400':'1#烧结矿',
								'L96040100':'石灰',
								'L96040200':'轻烧白云石',
								'L96053601':'钢渣',
								'HEAT_WGT':'炉重(KG)',
								'DOWNFURNACETIMES':'倒炉次数',
								'CARBONTEMPERATURE':'一倒温度(℃)',
								'FIRSTCATCHCARBONC':'一倒C%',
								'FIRSTCATCHCARBONP':'一倒P%',
								'SUBLANCE_AGE':'副枪枪龄',
								'SUBLANCE_INDEPTH':'副枪插入深度',
								'O_CONT':'定氧',
								'LEQHEIGH':'液面高度',
								'FIRSTCATCHOXYGENCONSUME':'一倒氧气耗量',
								'TIMEOFOXYGEN':'一倒供氧时间',
								'TOTALOXYGENCONSUME':'总供氧耗量',
								'N2CONSUME':'氮气耗量',
								'BEFARTEMP':'氩前温度',
								'SUM_BO_CSM':'总吹氧消耗',
								'D1_BO_CSM':'第一次吹氧消耗',
								'D2_BO_CSM':'第二次吹氧消耗',
								'D3_BO_CSM ':'第三次吹氧消耗',
								'D4_BO_CSM':'第四次吹氧消耗',
								'final_TEMP_VALUE':'最终测温值',
								'D1_TEMP_VALUE':'第一次测温值',
								'D2_TEMP_VALUE':'第二次测温值',
								'STEELWGT':'出钢量',
								'C':'C',
								'Si':'Si',
								'Mn':'Mn',
								'P':'P',
								'S':'S',
								'Al_T':'Al_T',
								'Al_S':'Al_S',
								'Ni':'Ni',
								'Cr':'Cr',
								'Cu ':'Cu',
								'Mo':'Mo',
								'V':'V',
								'Ti':'Ti',
								'Nb':'Nb',
								'W':'W',
								'Pb':'Pb',
								'Sn':'Sn',
								'AS':'AS',
								'Bi':'Bi',
								'B':'B',
								'Ca':'Ca',
								'N':'N',
								'Co':'Co',
								'Zr':'Zr',
								'Ce':'Ce',
								'Fe':'Fe',
								'TEMPOFARRIVE':'进站温度(℃)',
								'TEMPOFDEPARTURE':'出站温度(℃)',

	
                        }
