# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='steel_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_uid', models.CharField(blank=True, max_length=200)),
                ('final_price', models.FloatField(blank=True)),
                ('highest_price', models.FloatField(blank=True)),
                ('lowest_price', models.FloatField(blank=True)),
                ('count', models.FloatField(blank=True)),
                ('count_price', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_uid', models.CharField(blank=True, max_length=200)),
                ('classification', models.CharField(blank=True, max_length=200)),
                ('real_meaning', models.CharField(blank=True, max_length=200)),
                ('own_table', models.CharField(blank=True, max_length=200)),
                ('own_col', models.CharField(blank=True, max_length=200)),
                ('from_uid', models.CharField(max_length=200)),
                ('from_system', models.CharField(blank=True, max_length=200)),
                ('from_dept', models.CharField(blank=True, max_length=200)),
                ('from_table', models.CharField(blank=True, max_length=200)),
                ('from_col', models.CharField(blank=True, max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
