# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steelNetWgt', models.FloatField(blank=True)),
                ('arriveWgt', models.FloatField(blank=True)),
                ('leaveWgt', models.FloatField(blank=True)),
                ('materialWgt', models.FloatField(blank=True)),
                ('slagCondenserWgt', models.FloatField(blank=True)),
                ('compressedAirConsumption', models.FloatField(blank=True)),
                ('slagRemoveWgt', models.FloatField(blank=True)),
                ('n2GasConsumption', models.FloatField(blank=True)),
            ],
        ),
    ]
