# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_converter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='scrapWgt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='converter',
            name='slagWgt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='converter',
            name='steelWgt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
