#-*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_auto_20160520_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='external_eles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_price', models.FloatField(blank=True)),
                ('scrap', models.FloatField(blank=True)),
                ('cooking_coal', models.FloatField(blank=True)),
                ('iron_powder', models.FloatField(blank=True)),
                ('now_ore', models.FloatField(blank=True)),
                ('import_ore', models.FloatField(blank=True)),
                ('now_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_weight', models.FloatField(blank=True)),
                ('order_baseprice', models.FloatField(blank=True)),
                ('order_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TransRelationMultikey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_uid1', models.CharField(blank=True, max_length=200)),
                ('own_uid2', models.CharField(blank=True, max_length=200)),
                ('classification', models.CharField(blank=True, max_length=200)),
                ('real_meaning', models.CharField(blank=True, max_length=200)),
                ('own_table', models.CharField(blank=True, max_length=200)),
                ('own_col', models.CharField(blank=True, max_length=200)),
                ('from_uid1', models.CharField(max_length=200)),
                ('from_uid2', models.CharField(max_length=200)),
                ('from_system', models.CharField(blank=True, max_length=200)),
                ('from_dept', models.CharField(blank=True, max_length=200)),
                ('from_table', models.CharField(blank=True, max_length=200)),
                ('from_col', models.CharField(blank=True, max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
