# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_external_eles_sale_transrelationmultikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transrelationmultikey',
            name='remarks',
            field=models.CharField(max_length=200),
        ),
    ]
