# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_auto_20160719_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(blank=True, max_length=200)),
                ('orderItem', models.CharField(max_length=200, null=True)),
                ('dispListNo', models.CharField(max_length=200, null=True)),
                ('tradeNo', models.CharField(max_length=200, null=True)),
                ('orderItemWeight', models.CharField(max_length=200, null=True)),
                ('orderPrice', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
