# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0008_auto_20160721_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='transrelation',
            name='procedure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transrelationmultikey',
            name='procedure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
