# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0009_auto_20160726_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CONVERTER',
            new_name='BOF',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Sales',
        ),
    ]
