# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0013_auto_20160727_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kr',
            name='heatNo',
        ),
    ]
