# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0014_remove_kr_heatno'),
    ]

    operations = [
        migrations.AddField(
            model_name='kr',
            name='heatNo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
