# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0015_kr_heatno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custarea',
            fields=[
                ('custNo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('recName', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
