# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0016_custarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bof',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kr',
            name='id',
        ),
        migrations.AlterField(
            model_name='bof',
            name='heatNo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kr',
            name='heatNo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
