# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0020_auto_20160731_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SALES2_NOID_NOSTYLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compId', models.CharField(blank=True, max_length=100, null=True)),
                ('noId', models.CharField(blank=True, max_length=100, null=True)),
                ('noStyle', models.CharField(blank=True, max_length=100, null=True)),
                ('noCount', models.CharField(blank=True, max_length=100, null=True)),
                ('createEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('createDate', models.CharField(blank=True, max_length=100, null=True)),
                ('createTime', models.CharField(blank=True, max_length=100, null=True)),
                ('updateEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('updateDate', models.CharField(blank=True, max_length=100, null=True)),
                ('updateTime', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SALES2_NOID_RULEID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noId', models.CharField(blank=True, max_length=30)),
                ('ruleId', models.CharField(blank=True, max_length=30)),
                ('compId', models.CharField(blank=True, max_length=100, null=True)),
                ('ruleName', models.CharField(blank=True, max_length=100, null=True)),
                ('ruleType', models.CharField(blank=True, max_length=100, null=True)),
                ('ruleLength', models.CharField(blank=True, max_length=100, null=True)),
                ('ruleConstant', models.CharField(blank=True, max_length=100, null=True)),
                ('ruleRenew', models.CharField(blank=True, max_length=100, null=True)),
                ('createEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('createDate', models.CharField(blank=True, max_length=100, null=True)),
                ('createTime', models.CharField(blank=True, max_length=100, null=True)),
                ('updateEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('updateDate', models.CharField(blank=True, max_length=100, null=True)),
                ('updateTime', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
