# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0026_auto_20160801_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales2_orderno_orderitem',
            name='orderLengthC',
        ),
        migrations.RemoveField(
            model_name='sales2_orderno_orderitem',
            name='orderThickC',
        ),
        migrations.RemoveField(
            model_name='sales2_orderno_orderitem',
            name='orderWidthC',
        ),
    ]
