# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0027_auto_20160801_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='SALES2_REFID_SUBID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refId', models.CharField(blank=True, max_length=30)),
                ('subId', models.CharField(blank=True, max_length=30)),
                ('compId', models.CharField(blank=True, max_length=100, null=True)),
                ('valueA', models.CharField(blank=True, max_length=100, null=True)),
                ('valueB', models.CharField(blank=True, max_length=100, null=True)),
                ('valueC', models.CharField(blank=True, max_length=100, null=True)),
                ('valueD', models.CharField(blank=True, max_length=100, null=True)),
                ('valueE', models.CharField(blank=True, max_length=100, null=True)),
                ('valueF', models.CharField(blank=True, max_length=100, null=True)),
                ('valueG', models.CharField(blank=True, max_length=100, null=True)),
                ('valueH', models.CharField(blank=True, max_length=100, null=True)),
                ('createEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('createDate', models.CharField(blank=True, max_length=100, null=True)),
                ('createTime', models.CharField(blank=True, max_length=100, null=True)),
                ('updateEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('updateDate', models.CharField(blank=True, max_length=100, null=True)),
                ('updateTime', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
