# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0028_sales2_refid_subid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SALES_COLLECTNO',
            fields=[
                ('collectNo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('collectType', models.CharField(blank=True, max_length=100, null=True)),
                ('recOrderNo', models.CharField(blank=True, max_length=100, null=True)),
                ('warehouseNo', models.CharField(blank=True, max_length=100, null=True)),
                ('beginHarborId', models.CharField(blank=True, max_length=100, null=True)),
                ('endHarborId', models.CharField(blank=True, max_length=100, null=True)),
                ('shipName', models.CharField(blank=True, max_length=100, null=True)),
                ('ser', models.CharField(blank=True, max_length=100, null=True)),
                ('informDate', models.CharField(blank=True, max_length=100, null=True)),
                ('leaveHarborDate', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('loadShip', models.CharField(blank=True, max_length=100, null=True)),
                ('effectEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('effectDate', models.CharField(blank=True, max_length=100, null=True)),
                ('effectTime', models.CharField(blank=True, max_length=100, null=True)),
                ('unEffectEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('unEffectDate', models.CharField(blank=True, max_length=100, null=True)),
                ('unEffectTime', models.CharField(blank=True, max_length=100, null=True)),
                ('createEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('createDate', models.CharField(blank=True, max_length=100, null=True)),
                ('createTime', models.CharField(blank=True, max_length=100, null=True)),
                ('updateEmpNo', models.CharField(blank=True, max_length=100, null=True)),
                ('updateDate', models.CharField(blank=True, max_length=100, null=True)),
                ('updateTime', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sales_loadno',
            name='collectNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
