# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0029_auto_20160801_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sr_invid',
            name='errCode',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
