# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TransRelation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_import.BaseModel')),
                ('own_uid', models.CharField(blank=True, max_length=200)),
                ('classification', models.CharField(blank=True, max_length=200)),
                ('real_meaning', models.CharField(blank=True, max_length=200)),
                ('own_table', models.CharField(blank=True, max_length=200)),
                ('own_col', models.CharField(blank=True, max_length=200)),
                ('from_uid', models.CharField(max_length=200)),
                ('from_system', models.CharField(blank=True, max_length=200)),
                ('from_dept', models.CharField(blank=True, max_length=200)),
                ('from_table', models.CharField(blank=True, max_length=200)),
                ('from_col', models.CharField(blank=True, max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200)),
            ],
            bases=('data_import.basemodel',),
        ),
    ]
