# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRANSFORMATION_RELATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=200)),
                ('real_meaning', models.CharField(max_length=200)),
                ('own_col', models.CharField(max_length=200)),
                ('from_system', models.CharField(max_length=200)),
                ('from_dept', models.CharField(max_length=200)),
                ('from_table', models.CharField(max_length=200)),
                ('from_col', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('remarks1', models.CharField(max_length=200)),
            ],
        ),
    ]
