# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformation_relation',
            old_name='remarks1',
            new_name='ccx',
        ),
    ]
