"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
# choose settings between Developement and Deploy
import os
import platform

node = platform.node()
print(node)
dev_machines = ('cheng-cx','cheng-cx.local' )

if node in dev_machines:
    # folder My_Blog
    MyBlog = os.path.dirname(os.path.dirname(__file__))
    # project dir, contains static and media folder under DEV environment
    PROJECT_DIR = os.path.dirname(MyBlog)
    DEBUG = True
    DATABASES = {
        'default': {
            # 'ENGINE': 'django.db.backends.sqlite3',
            # 'NAME': os.path.join(My_Blog, 'db.sqlite3'),
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'qinggang',
            'USER': 'root',
            'PASSWORD': '123456',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }
    STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
    STATIC_URL = '/static/'
    MEDIA_ROOT = os.path.join(PROJECT_DIR, 'media')
    MEDIA_URL = '/media/'
    TEMPLATE_DIRS = [os.path.join(MyBlog, 'templates')]
    ALLOWED_HOSTS = ['*']
else:
    DEBUG = True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'qinggang',
            'USER': 'root',
            'PASSWORD': '123456',
            'HOST': '202.204.54.102',
            'PORT': '3306',
        },
        '1default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'qinggang',
        'USER': 'qinggang',
        'PASSWORD': 'qinggang',
        'HOST': '10.30.0.152',
        'PORT': '1521',
        },
        'qg': {
            'ENGINE': 'django.db.backends.oracle',
            'NAME': 'maksim',
            'USER': 'changxin',
            'PASSWORD': '123456',
            'HOST': 'localhost',
            'PORT': '1521',
        },
        'mes': {
            'ENGINE': 'django.db.backends.oracle',
            'NAME': 'mesdb2',#sid:mesdb2;service:mesdb
            'USER': 'xx_query',
            'PASSWORD': 'xxx',
            'HOST': 'xx.30.xx.17',
            'PORT': '1521',
        },
        'l2': {
            'ENGINE': 'django.db.backends.oracle',
            'NAME': 'qgil2db',
            'USER': 'xx_query',
            'PASSWORD': 'xxx',
            'HOST': 'xx.30.xx.17',
            'PORT': '1521',
        }
    }
    PROJECT_DIR = '/home/maksim/venv/qinggang/managesys'
    MEDIA_ROOT = '/home/maksim/venv/qinggang/media/'
    MEDIA_URL = '/media/'
    STATIC_ROOT = '/home/maksim/venv/qinggang/static/'
    STATIC_URL = '/static/'

    STATICFILES_DIRS = (
        os.path.join(PROJECT_DIR, 'static'),
    )

    TEMPLATE_DIRS = (
        os.path.join(PROJECT_DIR, 'templates'),
    )

    ALLOWED_HOSTS = [
        '*',
    ]

    # # cache entire site
    # MIDDLEWARE_CLASSES_ADDITION_FIRST = (
    #     'django.middleware.cache.UpdateCacheMiddleware',
    # )

    # MIDDLEWARE_CLASSES_ADDITION_LAST = (
    #     'django.middleware.cache.FetchFromCacheMiddleware',
    # )

    # CACHES = {
    #     'default': {
    #         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
    #         'LOCATION': '127.0.0.1:11211',
    #     }
    # }

